-- Add Super Admin User to the Database
-- This script inserts a default super admin account for testing
-- Password: SuperAdmin@123

USE library_db_1;

-- Insert Super Admin
-- Note: In production, you should hash passwords using bcrypt
-- For now, we'll store a bcrypt hash of "SuperAdmin@123"
INSERT INTO super_admins (first_name, last_name, email, national_id, password, phone, address, date_of_birth) 
VALUES (
    'Super',
    'Admin',
    'superadmin@saib.com',
    NULL, -- national_id can be NULL or a valid 16-digit number
    '$2a$10$XQKq8K8V3Y9P5h3J3K8V3uX8V3Y9P5h3J3K8V3uX8V3Y9P5h3J3K8', -- Placeholder hash (will be generated by backend)
    '+966-50-123-4567',
    'SAIB Library Headquarters, Riyadh',
    '1985-01-15'
);

-- Insert Regular Admin for testing
INSERT INTO admins (first_name, last_name, email, national_id, password, phone, address, date_of_birth) 
VALUES (
    'Regular',
    'Admin',
    'admin@saib.com',
    NULL,
    '$2a$10$XQKq8K8V3Y9P5h3J3K8V3uX8V3Y9P5h3J3K8V3uX8V3Y9P5h3J3K8', -- Placeholder hash
    '+966-50-123-4568',
    'SAIB Library Branch, Jeddah',
    '1990-05-20'
);

-- Insert a test member/customer
INSERT INTO members (first_name, last_name, email, password, phone, address, date_of_birth, membership_start_date) 
VALUES (
    'Test',
    'Customer',
    'customer@test.com',
    '$2a$10$XQKq8K8V3Y9P5h3J3K8V3uX8V3Y9P5h3J3K8V3uX8V3Y9P5h3J3K8', -- Placeholder hash
    '+966-50-123-4569',
    'Riyadh, Saudi Arabia',
    '1995-08-10',
    CURDATE()
);

-- Display the created accounts
SELECT 'Super Admins:' as 'Account Type';
SELECT super_admin_id as ID, first_name, last_name, email, phone FROM super_admins;

SELECT 'Admins:' as 'Account Type';
SELECT admin_id as ID, first_name, last_name, email, phone FROM admins;

SELECT 'Members:' as 'Account Type';
SELECT member_id as ID, first_name, last_name, email, phone FROM members;




